// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(_e) {
  return (_e.toString());
}

var JsError = {
  toString: toString
};

exports.JsError = JsError;
/* No side effect */
